// HOWXM server: noticias en tiempo real por WebSocket. Sin dependencias (Node 18+).
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
try{fs.readFileSync('.env','utf8').split('\n').forEach(l=>{const m=l.match(/^\s*([A-Z_]+)\s*=\s*(.*)\s*$/);if(m&&!(m[1] in process.env))process.env[m[1]]=m[2].replace(/^["']|["']$/g,'')})}catch(e){}
const E=process.env,PORT=+E.PORT||3000,KEEP=300,UA='Mozilla/5.0 (compatible; HOWXM/1.0)';
/* ---------- fuentes (edita a gusto; los feeds que fallen se omiten y se reintentan despacio) ---------- */
const RSS=[['FXStreet','https://www.fxstreet.com/rss/news'],['Investing.com','https://www.investing.com/rss/news.rss'],['Investing.com Forex','https://www.investing.com/rss/news_1.rss'],['MarketWatch','https://feeds.content.dowjones.io/public/rss/mw_topstories'],['MarketWatch Pulse','https://feeds.content.dowjones.io/public/rss/mw_marketpulse'],['Benzinga','https://www.benzinga.com/feed'],['Cointelegraph','https://cointelegraph.com/rss'],['CoinDesk','https://www.coindesk.com/arc/outboundfeeds/rss/']].concat(E.EXTRA_RSS?E.EXTRA_RSS.split(',').map(u=>[new URL(u).hostname,u.trim()]):[]);
/* ---------- etiquetado, impacto y sentimiento (reglas locales, sin IA de pago) ---------- */
const ASSETS=[['#XAUUSD',/\b(gold|xau|bullion|precious metals?)\b/i],['#BTCUSD',/\b(bitcoin|btc|crypto(currenc(y|ies))?|spot bitcoin etfs?)\b/i],['#ETHUSD',/\b(ethereum|ether|eth)\b/i],['#EURUSD',/\b(euro\b|eur\/usd|ecb|lagarde|eurozone)/i],['#USD',/\b(dollar|dxy|fed\b|fomc|powell|treasur(y|ies)|yields?|cpi|nfp|payrolls?|inflation)\b/i],['#OIL',/\b(oil|crude|opec|brent|wti)\b/i],['#SPX',/\b(s&p ?500|nasdaq|dow jones|wall street|stocks?)\b/i],['#TSLA',/\btesla\b/i],['#NVDA',/\bnvidia\b/i],['#AAPL',/\bapple\b/i]];
const HIGH=/\b(cpi|ipc|inflation|nfp|non-?farm|payrolls?|fomc|rate (decision|hike|cut)s?|interest rates?|fed (holds|hikes|cuts|raises|lowers)|ecb|boj|boe|gdp|pce|powell|lagarde|jobs report|unemployment rate|etf (approval|approved|rejected)|halving|hack(ed)?|exploit|bankrupt(cy)?|default|sanctions?|opec|tariffs?|war\b|emergency)\b/i,MED=/\b(pmi|retail sales|ism|earnings|guidance|yields?|treasury|dollar|dxy|oil|crude|gold|bitcoin|crypto|jobless|housing|consumer (confidence|sentiment)|central bank|speech|minutes|outflows?|inflows?)\b/i;
const BULL=/\b(surge|soar|rall(y|ies)|jump|rise|gain|record high|breakout|beat|upgrade|inflows?|approval|approved|adoption|dovish|rate cut|safe[- ]haven|bullish|strong|optimis\w+|recover\w*)\b/i,BEAR=/\b(plunge|slump|tumble|drop|fall|fell|decline|sell-?off|crash|miss|downgrade|outflows?|hack(ed)?|ban|lawsuit|hawkish|rate hike|bearish|weak|fear|recession|liquidat\w+|crackdown|slips?|slides?|dips?|eases|retreats?|pares)\b/i;
const HINT={'#XAUUSD':{bull:/\b(rate cuts?|dovish|weaker dollar|safe[- ]haven|geopolitic\w*|central bank (buying|purchases))\b/i,bear:/\b(rate hikes?|hawkish|hotter[- ]than[- ]expected|higher[- ]than[- ]expected|stronger dollar|dollar (rises|gains|jumps)|yields? (rise|surge|jump)|etf outflows?)\b/i},'#BTCUSD':{bull:/\b(etf (inflows?|approv\w+)|adoption|institutional|halving)\b/i,bear:/\b(ban|crackdown|hack\w*|outflows?|liquidat\w+|sec (sues|charges))\b/i}};
function enrich(it){const t=it.title+' '+(it.summary||''),tags=new Set(it.tags||[]);ASSETS.forEach(([g,r])=>{if(r.test(t))tags.add(g)});
 const impact=HIGH.test(it.title)?'high':(MED.test(t)||tags.size)?'medium':'low';let s=it.score;if(s==null){const b=BULL.test(it.title)?1:0,r=BEAR.test(it.title)?1:0;s=(b-r)*.5}
 const by={};tags.forEach(g=>{let v=s;const h=HINT[g];if(h){const a=h.bull.test(t),b=h.bear.test(t);if(a||b)v=(a?.7:0)-(b?.7:0)}by[g]=Math.max(-1,Math.min(1,v))});
 return{id:crypto.createHash('sha1').update(it.url||it.title).digest('hex').slice(0,12),title:it.title.trim(),url:it.url,source:it.source,t:it.t||Date.now(),tags:[...tags],impact,sent:s>.15?'bullish':s<-.15?'bearish':'neutral',score:+s.toFixed(2),by}}
/* ---------- estado y difusion ---------- */
const store=[],seen=new Set();let cal=[];const clients=new Set();
function ingest(raw){let n=0;raw.forEach(r=>{if(!r.title||!r.url)return;const k=crypto.createHash('sha1').update(r.url).digest('hex');if(seen.has(k))return;seen.add(k);if(seen.size>5000)seen.delete(seen.values().next().value);
 if(r.t&&Date.now()-r.t>36e5*6)return;const it=enrich(r);if(E.FILTER_NOISE!=='0'&&it.impact==='low'&&!it.tags.length)return;store.unshift(it);if(store.length>KEEP)store.pop();broadcast({type:'news',item:it});n++});return n}
/* ---------- WebSocket minimo (RFC 6455, solo servidor->cliente) ---------- */
function frame(op,buf){const l=buf.length,h=l<126?Buffer.from([0x80|op,l]):l<65536?Buffer.from([0x80|op,126,l>>8,l&255]):(()=>{const b=Buffer.alloc(10);b[0]=0x80|op;b[1]=127;b.writeBigUInt64BE(BigInt(l),2);return b})();return Buffer.concat([h,buf])}
function send(s,o){if(!s.destroyed)s.write(frame(1,Buffer.from(JSON.stringify(o))))}
function broadcast(o){const f=frame(1,Buffer.from(JSON.stringify(o)));clients.forEach(s=>{try{s.write(f)}catch(e){clients.delete(s)}})}
const srv=http.createServer((q,r)=>{const u=new URL(q.url,'http://x');if(E.ALLOW_ORIGIN)r.setHeader('Access-Control-Allow-Origin',E.ALLOW_ORIGIN);
 if(u.pathname==='/api/news'){r.setHeader('Content-Type','application/json');return r.end(JSON.stringify(store.slice(0,100)))}
 if(u.pathname==='/api/calendar'){r.setHeader('Content-Type','application/json');return r.end(JSON.stringify(cal))}
 if(u.pathname==='/healthz')return r.end('ok');
 const P1=path.join(__dirname,'public'),want=u.pathname==='/'?'index.html':path.normalize(u.pathname).replace(/^(\.\.[\/\\])+/,'');
 const cands=[path.join(P1,want)].concat(want==='index.html'?[path.join(__dirname,'index.html')]:[]);
 const f=cands.find(x=>x.startsWith(__dirname)&&fs.existsSync(x)&&fs.statSync(x).isFile());
 if(!f){r.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return r.end('HOWXM: el servidor funciona, pero falta el archivo de la pagina (index.html). Sube index.html al repositorio, dentro de la carpeta public o en la raiz.')}
 fs.readFile(f,(e,d)=>{if(e)return r.writeHead(500).end('error');r.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream');r.end(d)})});
srv.on('upgrade',(q,s)=>{if(!/^\/ws/.test(q.url)||!q.headers['sec-websocket-key']||clients.size>=(+E.MAX_CLIENTS||500))return s.destroy();
 s.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+crypto.createHash('sha1').update(q.headers['sec-websocket-key']+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64')+'\r\n\r\n');
 clients.add(s);s.alive=true;send(s,{type:'hello',news:store.slice(0,80),calendar:cal,sources:status()});
 s.on('data',b=>{const op=b[0]&15;if(op===8){clients.delete(s);s.end(frame(8,Buffer.alloc(0)))}else if(op===10)s.alive=true;else if(op===9)s.write(frame(10,Buffer.alloc(0)))});
 const gone=()=>{clients.delete(s);s.destroy()};s.on('close',gone);s.on('error',gone)});
setInterval(()=>clients.forEach(s=>{if(!s.alive){clients.delete(s);return s.destroy()}s.alive=false;try{s.write(frame(9,Buffer.alloc(0)))}catch(e){}}),25000);
/* ---------- recolectores (respetan los limites de los planes gratuitos) ---------- */
const st={};function status(){return Object.entries(st).map(([n,v])=>({n,ok:v.ok,last:v.last,err:v.err}))}
async function get(u,ms){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms||9000);try{const r=await fetch(u,{headers:{'User-Agent':UA,Accept:'*/*'},signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
const dec=s=>s.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#0?39;|&apos;/g,"'").replace(/\s+/g,' ').trim();
function parseRSS(x,src){const out=[],blocks=x.match(/<(item|entry)[\s>][\s\S]*?<\/\1>/g)||[];blocks.forEach(b=>{const g=t=>{const m=b.match(new RegExp('<'+t+'[^>]*>([\\s\\S]*?)</'+t+'>','i'));return m?dec(m[1]):''};let url=g('link');if(!url){const m=b.match(/<link[^>]*href="([^"]+)"/i);url=m?m[1]:''}const d=Date.parse(g('pubDate')||g('published')||g('updated')||g('dc:date'));out.push({title:g('title'),url,summary:g('description')||g('summary'),source:src,t:isNaN(d)?Date.now():Math.min(d,Date.now())})});return out}
function every(name,ms,fn){st[name]={ok:false,fails:0};const run=async()=>{try{await fn();st[name]={ok:true,last:Date.now(),fails:0}}catch(e){const f=(st[name].fails||0)+1;st[name]={ok:false,fails:f,err:String(e.message||e).slice(0,80),last:st[name].last};if(f===1)console.log('[!] '+name+': '+st[name].err)}setTimeout(run,Math.min(ms*Math.pow(2,Math.min(st[name].fails||0,5)),ms*16))};setTimeout(run,Math.random()*3000)}
RSS.forEach(([n,u])=>every(n,+E.RSS_MS||60000,async()=>{ingest(parseRSS(await get(u),n))}));
if(E.FINNHUB_KEY)['general','forex','crypto'].forEach(c=>every('Finnhub '+c,60000,async()=>{const j=JSON.parse(await get('https://finnhub.io/api/v1/news?category='+c+'&token='+E.FINNHUB_KEY));ingest(j.map(x=>({title:x.headline,url:x.url,summary:x.summary,source:'Finnhub / '+(x.source||''),t:x.datetime*1000})))}));
if(E.ALPHAVANTAGE_KEY)every('Alpha Vantage',3600000,async()=>{const j=JSON.parse(await get('https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=economy_macro,financial_markets,blockchain&limit=50&apikey='+E.ALPHAVANTAGE_KEY));if(j.Note||j.Information)throw new Error('limite diario alcanzado');ingest((j.feed||[]).map(x=>({title:x.title,url:x.url,summary:x.summary,source:'Alpha Vantage / '+x.source,score:Math.max(-1,Math.min(1,x.overall_sentiment_score*2)),tags:(x.ticker_sentiment||[]).slice(0,3).map(t=>'#'+t.ticker.replace(/^(CRYPTO|FOREX):/,'')),t:Date.parse(x.time_published.replace(/(\d{4})(\d\d)(\d\d)T(\d\d)(\d\d)(\d\d)/,'$1-$2-$3T$4:$5:$6Z'))})))});
if(E.POLYGON_KEY)every('Polygon',90000,async()=>{const j=JSON.parse(await get('https://api.polygon.io/v2/reference/news?limit=30&order=desc&apiKey='+E.POLYGON_KEY));ingest((j.results||[]).map(x=>({title:x.title,url:x.article_url,summary:x.description,source:'Polygon / '+((x.publisher||{}).name||''),tags:(x.tickers||[]).slice(0,3).map(t=>'#'+t.replace(/^X:/,'')),t:Date.parse(x.published_utc)})))});
if(E.NEWSAPI_KEY)every('NewsAPI',1800000,async()=>{const j=JSON.parse(await get('https://newsapi.org/v2/everything?language=en&sortBy=publishedAt&pageSize=40&q='+encodeURIComponent('"Federal Reserve" OR bitcoin OR gold OR inflation')+'&apiKey='+E.NEWSAPI_KEY));ingest((j.articles||[]).map(x=>({title:x.title,url:x.url,summary:x.description,source:'NewsAPI / '+((x.source||{}).name||''),t:Date.parse(x.publishedAt)})))});
if(E.CALENDAR!=='0')every('Calendario',1200000,async()=>{const j=JSON.parse(await get('https://nfs.faireconomy.media/ff_calendar_thisweek.json'));cal=j.filter(x=>/^(High|Medium)$/.test(x.impact)).map(x=>({t:Date.parse(x.date),title:x.title,country:x.country,impact:x.impact.toLowerCase(),forecast:x.forecast,previous:x.previous}));broadcast({type:'calendar',calendar:cal})});
if(E.MOCK==='1'){const M=[['Fed signals rate cut path as inflation cools, gold rallies','Mock'],['Bitcoin ETF outflows deepen as dollar strengthens','Mock'],['US CPI beats expectations, yields jump','Mock'],['Tesla opens new factory line','Mock']];let i=0;setInterval(()=>{const m=M[i++%M.length];ingest([{title:m[0]+' #'+i,url:'https://example.com/mock/'+i,source:m[1]}])},8000)}
srv.listen(PORT,()=>{console.log('Pagina (index.html): '+(fs.existsSync(path.join(__dirname,'public','index.html'))?'public/index.html':fs.existsSync(path.join(__dirname,'index.html'))?'index.html (raiz)':'NO ENCONTRADA. Archivos aqui: '+fs.readdirSync(__dirname).join(', ')));console.log('HOWXM en http://localhost:'+PORT+'  (fuentes RSS: '+RSS.length+(E.FINNHUB_KEY?', Finnhub':'')+(E.ALPHAVANTAGE_KEY?', AlphaVantage':'')+(E.POLYGON_KEY?', Polygon':'')+(E.NEWSAPI_KEY?', NewsAPI':'')+')')});
module.exports={enrich,parseRSS};
